name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # macOS builds
          - os: macos-latest
            goos: darwin
            goarch: amd64
            binary_name: markdown-vector-mcp-macos-intel
          - os: macos-latest
            goos: darwin
            goarch: arm64
            binary_name: markdown-vector-mcp-macos-apple-silicon
          # Linux builds
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            binary_name: markdown-vector-mcp-linux-x64
          - os: ubuntu-latest
            goos: linux
            goarch: arm64
            binary_name: markdown-vector-mcp-linux-arm64
          # Windows builds
          - os: windows-latest
            goos: windows
            goarch: amd64
            binary_name: markdown-vector-mcp-windows-x64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Set up MSYS2 and dependencies (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          # Install MSYS2 packages using chocolatey's msys2
          C:/msys64/usr/bin/pacman.exe -Syu --noconfirm
          C:/msys64/usr/bin/pacman.exe -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-sqlite3

      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        env:
          CGO_ENABLED: 1
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          # Use pre-installed MSYS2
          MSYS_ROOT="C:/msys64"

          export PATH="$MSYS_ROOT/mingw64/bin:$PATH"
          export PKG_CONFIG_PATH="$MSYS_ROOT/mingw64/lib/pkgconfig"

          # Use Windows-style paths for CGO
          export CGO_CFLAGS="-IC:/msys64/mingw64/include"
          export CGO_LDFLAGS="-LC:/msys64/mingw64/lib"

          # Debug: check if sqlite3.h exists
          echo "Checking for sqlite3.h..."
          ls -la C:/msys64/mingw64/include/sqlite3.h || echo "sqlite3.h not found"

          # Debug: show gcc location
          which gcc
          gcc --version

          go build -ldflags="-s -w" -o ${{ matrix.binary_name }} cmd/main.go

      - name: Build (Unix)
        if: matrix.os != 'windows-latest'
        env:
          CGO_ENABLED: 1
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          if [ "${{ matrix.goarch }}" = "arm64" ] && [ "${{ matrix.goos }}" = "linux" ]; then
            export CC=aarch64-linux-gnu-gcc
          fi
          go build -ldflags="-s -w" -o ${{ matrix.binary_name }} cmd/main.go
        shell: bash

      - name: Create tarball (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          tar -czf ${{ matrix.binary_name }}.tar.gz ${{ matrix.binary_name }}
          shasum -a 256 ${{ matrix.binary_name }}.tar.gz > ${{ matrix.binary_name }}.tar.gz.sha256

      - name: Create zip (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Compress-Archive -Path ${{ matrix.binary_name }} -DestinationPath ${{ matrix.binary_name }}.zip
          (Get-FileHash -Algorithm SHA256 ${{ matrix.binary_name }}.zip).Hash | Out-File -FilePath ${{ matrix.binary_name }}.zip.sha256

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.binary_name }}
          path: |
            ${{ matrix.binary_name }}.*

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
